version: "3.9"

services:
  db:
    image: postgres:15
    container_name: prostreamer_db
    restart: always
    environment:
      POSTGRES_USER: prostreamer
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: prostreamerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: prostreamer_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
